name = "sharing"
compatibility_date = "2026-06-05"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

# 配置环境变量
[vars]
PORT = "3100"

# R2 存储绑定配置
[[r2_buckets]]
binding = "FILES_BUCKET"
bucket_name = "sharing-files"
